global_costmap:
  global_frame: map
  robot_base_frame: base_link
  rolling_window: false
  track_unknown_spacec: true

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser, type: "costmap_2d::VoxelLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
    