shutdown_costmaps: false
controller_frequency: 5.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

# recovery_behavior_enabled: true
recovery_behaviors:
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: clear_costmap_recovery
    type: clear_costmap_recovery/ClearCostmapRecovery

recovery_enabled: true
recovery_patience: 15.0
max_rotational_vel : 0.2
acc_lim_th: 2.0
yaw_goal_tolerance: 0.1
min_in_place_rotational_vel:  0.2

