base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.25  #max 3.0
  min_vel_x: -0.25

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.25
  min_vel_trans:  0.11

  max_vel_theta: 0.22 #max 3.5
  min_vel_theta: 0.11

  min_in_place_vel_theta: 0.15

  acc_lim_x: 1.2 #0.8
  acc_lim_y: 0.0
  acc_lim_theta: 2.0 #1.7

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  
  holonomic_robot: false
