ninjabot_msgs/Ws2812b front
ninjabot_msgs/Ws2812b rear
ninjabot_msgs/Ws2812b left
ninjabot_msgs/Ws2812b right
ninjabot_msgs/Ws2812b front_left
ninjabot_msgs/Ws2812b front_right
ninjabot_msgs/Ws2812b rear_left
ninjabot_msgs/Ws2812b rear_right
# true - full strip animation
# false - individual led strip
bool global_anim
# 1 - steady
# 2 - blink twice
# 3 - blick trice
# 4 - flow
# 5 - dimming
ninjabot_msgs/Ws2812b body