ninjabot_msgs/Ws2812b front
ninjabot_msgs/Ws2812b rear
ninjabot_msgs/Ws2812b left
ninjabot_msgs/Ws2812b right
ninjabot_msgs/Ws2812b front_left
ninjabot_msgs/Ws2812b front_right
ninjabot_msgs/Ws2812b rear_left
ninjabot_msgs/Ws2812b rear_right
# true - full strip animation
# false - individual led strip
bool global_anim
# steady        1
# dimming       2
# flow n cut    3
# hue flow      4
# rainbow flow  5
ninjabot_msgs/Ws2812b body
